### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pjoshi1**
Edited a typo

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
"a la" is a [valid phrase in American English](https://www.dictionary.com/browse/a-la) -- your change here changes semantics, but it doesn't fix a typo, per se.

I'm curious what made it sound wrong to you, though -- I wonder if others have been confused by that sentence?

**Comment by ErichDonGubler** [comment]
Also, welcome to NYAR! It's great to see another first-time contributor here. :) Feel free to make other PRs and suggestions in issues as you see fit -- I'm sure there's lots of details that could be updated, grammar that needs fixing, etc.

**Comment by pjoshi1** [comment]
Hi Erich, 
Oops! I didn't know that. Since I am not a native speaker of the language, and have never seen that phrase ever before, I think that's what made it sound wrong to me. 
I am pretty sure it's not just me, but there are a lot of Rust users out there who wouldn't know what that phrase means, however since it's only a search away, I think it can be kept there. 
Nonetheless, my suggestion is that since a lot of Rustaceans are non native speakers of English, it is best to keep the documentations' language as simple as possible.

**Comment by ErichDonGubler** [comment]
I've just created a PR that should solve the issue you've described here: https://github.com/not-yet-awesome-rust/not-yet-awesome-rust/pull/55

Let's continue the conversation there!

**Pull request closed without merging**
